document.addEventListener("DOMContentLoaded",function(){vbIcons();});window.MIFRM_CONFIG={similarTopics:{count:6},home:{topicsCount:10,repliesCount:10,loadMoreStep:10},notif:{topicsCount:20,repliesCount:20,maxItems:50},signup:{email:"hamdiuludag.news@blogger.com",bloggerMail:"hamdiuludag.news@blogger.com",clientId:"290017525033-k26glhndr237smhmu9kqnu7i405je9fa.apps.googleusercontent.com"},stats:{show:true},footer:{privacy:"https://cdn.mifrm.eu.cc/#turkce",kvkk:"https://cdn.mifrm.eu.cc/#turkce",refund:"https://cdn.mifrm.eu.cc/#turkce",rules:"https://mifrm.blogspot.com/2026/06/forum-kurallar.html",terms:"https://cdn.mifrm.eu.cc/#turkce",contact:"https://cdn.mifrm.eu.cc/#turkce"},linkRedirect:{enabled:true,countdown:5,adHtml:""},pageRedirect:{countdown:10,target:"/",adHtml:""}};window.MFG=function(path,def){try{var o=window.MIFRM_CONFIG,p=path.split(".");for(var i=0;i<p.length;i++){o=o[p[i]];if(o===undefined||o===null)return def;}
return o;}catch(e){return def;}};document.addEventListener("DOMContentLoaded",function(){var fmap={privacy:"vb-foot-privacy",kvkk:"vb-foot-kvkk",refund:"vb-foot-refund",rules:"vb-foot-rules",terms:"vb-foot-terms",contact:"vb-foot-contact"};Object.keys(fmap).forEach(function(k){var el=document.getElementById(fmap[k]);if(!el)return;var url=MFG("footer."+k,"#");el.setAttribute("href",url||"#");if(!url||url==="#"){el.style.pointerEvents="none";el.style.opacity="0.55";}});if(MFG("stats.show",true)===false){var st=document.getElementById("statistics");if(st)st.style.display="none";}});(function(){var THEMES=['default','zumrut','gece','bordo','lacivert'];function applyTheme(name,persist){if(THEMES.indexOf(name)===-1)name='default';if(name==='default'){document.documentElement.removeAttribute('data-vb-theme');}
else{document.documentElement.setAttribute('data-vb-theme',name);}
if(persist){try{localStorage.setItem('vbTheme',name);}catch(e){}}
var opts=document.querySelectorAll('.vb-theme-opt');for(var i=0;i<opts.length;i++){var on=opts[i].getAttribute('data-vb-theme-value')===name;opts[i].classList.toggle('vb-active',on);opts[i].setAttribute('aria-checked',on?'true':'false');}}
function setMenu(box,toggle,menu,open){box.classList.toggle('vb-theme-open',open);toggle.setAttribute('aria-expanded',open?'true':'false');menu.setAttribute('aria-hidden',open?'false':'true');if(open){menu.removeAttribute('inert');}else{menu.setAttribute('inert','');}}
document.addEventListener('DOMContentLoaded',function(){var saved='default';try{saved=localStorage.getItem('vbTheme')||'default';}catch(e){}
applyTheme(saved,false);var opts=document.querySelectorAll('.vb-theme-opt');for(var i=0;i<opts.length;i++){opts[i].addEventListener('click',function(){applyTheme(this.getAttribute('data-vb-theme-value'),true);var box=this.closest('.vb-theme-box');var toggle=box?box.querySelector('#vbThemeToggle'):null;var menu=box?box.querySelector('#vbThemeMenu'):null;if(box&&toggle&&menu)setMenu(box,toggle,menu,false);});}
var box=document.getElementById('vbThemeSwitch');var toggle=document.getElementById('vbThemeToggle');var menu=document.getElementById('vbThemeMenu');if(box&&toggle&&menu){toggle.addEventListener('click',function(){setMenu(box,toggle,menu,!box.classList.contains('vb-theme-open'));});document.addEventListener('click',function(e){if(box.classList.contains('vb-theme-open')&&!box.contains(e.target))setMenu(box,toggle,menu,false);});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&box.classList.contains('vb-theme-open')){setMenu(box,toggle,menu,false);toggle.focus();}});}});})();(function(){function txt(id){var e=document.getElementById(id);return e?(e.innerText||e.textContent||""):"";}
function parseKV(s){var o={};s.split(/\r?\n/).forEach(function(line){line=line.trim();if(!line||line.charAt(0)==="#")return;var i=line.indexOf("=");if(i<0)return;var k=line.slice(0,i).trim().toLowerCase();var v=line.slice(i+1).trim();if(k)o[k]=v;});return o;}
var kv=parseKV(txt("mifrm-settings-data"));var C=window.MIFRM_CONFIG=window.MIFRM_CONFIG||{};C.similarTopics=C.similarTopics||{};C.home=C.home||{};C.notif=C.notif||{};C.signup=C.signup||{};C.stats=C.stats||{};C.footer=C.footer||{};C.linkRedirect=C.linkRedirect||{};C.pageRedirect=C.pageRedirect||{};function num(key,cur){var v=kv[key];if(v===undefined||v==="")return cur;var n=parseInt(v,10);return isNaN(n)?cur:n;}
function str(key,cur){var v=kv[key];return(v===undefined)?cur:v;}
function bool(key,cur){var v=kv[key];if(v===undefined)return cur;v=(""+v).toLowerCase();return(v==="evet"||v==="true"||v==="1"||v==="acik"||v==="açık"||v==="aç"||v==="on"||v==="var");}
C.similarTopics.count=num("benzer_konular",C.similarTopics.count);C.home.topicsCount=num("anasayfa_konular",C.home.topicsCount);C.home.repliesCount=num("anasayfa_cevaplar",C.home.repliesCount);C.home.loadMoreStep=num("daha_fazla_adim",C.home.loadMoreStep);C.notif.topicsCount=num("bildirim_konular",C.notif.topicsCount);C.notif.repliesCount=num("bildirim_cevaplar",C.notif.repliesCount);C.notif.maxItems=num("bildirim_max",C.notif.maxItems);C.signup.email=str("uyelik_mail",C.signup.email);C.signup.bloggerMail=str("blogger_mail",C.signup.bloggerMail);C.signup.clientId=str("google_client_id",C.signup.clientId);C.stats.show=bool("istatistik_goster",C.stats.show!==false);C.footer.privacy=str("footer_gizlilik",C.footer.privacy);C.footer.kvkk=str("footer_kvkk",C.footer.kvkk);C.footer.refund=str("footer_iade",C.footer.refund);C.footer.rules=str("footer_kurallar",C.footer.rules);C.footer.terms=str("footer_sozlesme",C.footer.terms);C.footer.contact=str("footer_iletisim",C.footer.contact);C.linkRedirect.enabled=bool("link_yonlendirme",C.linkRedirect.enabled!==false);C.linkRedirect.countdown=num("link_geri_sayim",C.linkRedirect.countdown);C.pageRedirect.countdown=num("sayfa_geri_sayim",C.pageRedirect.countdown);C.pageRedirect.target=str("sayfa_hedef",C.pageRedirect.target);function adHtml(id){var e=document.getElementById(id);if(!e)return"";var t=(e.innerText||e.textContent||"").trim();if(!t||t.indexOf("REKLAM-ALANI")>=0)return"";return e.innerHTML.trim();}
C.linkRedirect.adHtml=adHtml("mifrm-ad-link");C.pageRedirect.adHtml=adHtml("mifrm-ad-page");})();var VB_NOTIF_KEY="vbN3";var VB_TOKEN_KEY="vbToken";var VB_TOKEN_EXP="vbTokenExp";var VB_TTL=43200000;var VB_PER_PAGE=10;var _vbAllPosts=[];var _vbShown=MFG("home.topicsCount",10);var _cmtShown=MFG("home.repliesCount",10);var _cmtAllEntries=[];var _cmtTopics=[];var _vbTimer=null;var _avatarCache={};var VB_MONTHS_TR=["Oca","Şub","Mar","Nis","May","Haz","Tem","Ağu","Eyl","Eki","Kas","Ara"];function safeText(t){if(t==null)return"";var d=document.createElement("div");d.textContent=String(t);return d.innerHTML;}
function cleanAuthor(n){if(!n||n==="Anonymous"||n==="İsimsiz"||n==="anonymous")return"Misafir";return String(n);}
function pad2(n){return(""+n).padStart(2,"0");}
function formatDate(iso){if(!iso)return"";var d=new Date(iso);if(isNaN(d.getTime()))return String(iso);var now=new Date();if(d.toDateString()===now.toDateString()){return"Bugün "+pad2(d.getHours())+":"+pad2(d.getMinutes());}
return d.getDate()+" "+VB_MONTHS_TR[d.getMonth()]+" "+d.getFullYear()
+", "+pad2(d.getHours())+":"+pad2(d.getMinutes());}
function formatDateShort(iso){if(!iso)return"—";var d=new Date(iso);if(isNaN(d.getTime()))return"—";return d.getDate()+" "+VB_MONTHS_TR[d.getMonth()]+" "+d.getFullYear();}
function getAltLink(entry){if(!entry||!Array.isArray(entry.link))return null;for(var i=0;i<entry.link.length;i++){if(entry.link[i].rel==="alternate")return entry.link[i];}
return null;}
function getAuthorName(entry){try{return cleanAuthor(entry.author[0].name.$t);}catch(e){return"Misafir";}}
function getAuthorImg(entry){try{var img=entry.author[0]["gd$image"];if(img&&img.src&&img.src.indexOf("silhouette")===-1&&img.src.indexOf("placeholder")===-1){return img.src;}}catch(e){}
return null;}
function getAuthorUri(entry){try{return entry.author[0].uri.$t||"";}catch(e){return"";}}
function tsOf(iso){if(!iso)return 0;var t=Date.parse(iso);return isNaN(t)?0:t;}
function buildAvatarCache(entries){entries.forEach(function(e){var name=getAuthorName(e);if(_avatarCache[name])return;var img=getAuthorImg(e);if(img)_avatarCache[name]=img;});}
function applyAvatarCache(){document.querySelectorAll("[data-avatar-author]").forEach(function(el){var name=el.getAttribute("data-avatar-author");if(!name||!_avatarCache[name])return;el.innerHTML='<img src="'+_avatarCache[name]
+'" alt="'+name
+'" loading="lazy" style="width:100%;height:100%;object-fit:cover;">';});}
var _fCache={};var _fTTL=900000;function cachedFetch(url){var now=Date.now();var c=_fCache[url];if(c&&(now-c.ts)<_fTTL)return Promise.resolve(c.data);return fetch(url).then(function(r){return r.ok?r.json():null;}).catch(function(){return null;}).then(function(d){_fCache[url]={ts:now,data:d};return d;});}function loadPageAvatars(){if(!document.querySelector("[data-avatar-author]"))return;cachedFetch("/feeds/posts/summary?alt=json&max-results=500").then(function(data){buildAvatarCache((data&&data.feed&&data.feed.entry)||[]);applyAvatarCache();});}
function vbGetToken(){try{var exp=parseInt(localStorage.getItem(VB_TOKEN_EXP)||"0",10);if(exp&&Date.now()>exp){localStorage.removeItem(VB_TOKEN_KEY);localStorage.removeItem(VB_TOKEN_EXP);return null;}
return localStorage.getItem(VB_TOKEN_KEY)||null;}catch(e){return null;}}
function vbSaveToken(tk,expiresIn){try{var exp=Date.now()+((parseInt(expiresIn,10)||3600)-60)*1000;localStorage.setItem(VB_TOKEN_KEY,tk);localStorage.setItem(VB_TOKEN_EXP,String(exp));}catch(e){}}
function vbClearToken(){try{localStorage.removeItem(VB_TOKEN_KEY);localStorage.removeItem(VB_TOKEN_EXP);}catch(e){}}
function vbLoadUserProfile(token){var VBU="vbUser3";var saved=null;try{saved=JSON.parse(localStorage.getItem(VBU));}catch(e){}function applyProfile(name,picture){window._vbUserName=name;var nameEl=document.getElementById("mifrm-user-name");var avatarEl=document.getElementById("mifrm-user-avatar");if(nameEl)nameEl.textContent=name||"Kullanıcı";if(avatarEl){if(picture){avatarEl.innerHTML='<img src="'+picture+'" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover;border-radius:50%;display:block;">';}else{avatarEl.innerHTML='<i aria-hidden="true" data-lucide="user"></i>';vbIcons(avatarEl);}}var panel=document.getElementById("mifrm-user-panel");if(panel)panel.classList.add("active");}if(saved&&saved.name){applyProfile(saved.name,saved.picture||null);return;}fetch("https://www.googleapis.com/oauth2/v3/userinfo",{headers:{"Authorization":"Bearer "+token}}).then(function(r){return r.ok?r.json():null;}).catch(function(){return null;}).then(function(d){if(!d)return;var name=d.name||d.email||"Kullanıcı";var picture=d.picture||null;try{localStorage.setItem(VBU,JSON.stringify({name:name,picture:picture}));}catch(e){}applyProfile(name,picture);});}
function vbToast(title,desc){var box=document.getElementById("forumLiveNotification");if(!box)return;var t=document.getElementById("notifyTitle");var d=document.getElementById("notifyDesc");if(t)t.textContent=title||"";if(d)d.textContent=desc||"";box.style.display="flex";clearTimeout(box._vbt);box._vbt=setTimeout(function(){box.style.display="none";},6000);}
function vbCloseToast(){var box=document.getElementById("forumLiveNotification");if(box){clearTimeout(box._vbt);box.style.display="none";}}
function openMifrm(){var el=document.getElementById("mifrm-overlay");if(el)el.classList.add("active");}
function closeMifrm(){var el=document.getElementById("mifrm-overlay");if(el)el.classList.remove("active");}
function setMifrmStatus(msg,cls){var el=document.getElementById("mifrm-status");if(!el)return;el.textContent=msg||"";el.className="mifrm-status"+(cls?" "+cls:"");}
document.addEventListener("DOMContentLoaded",function(){var overlay=document.getElementById("mifrm-overlay");if(overlay){overlay.addEventListener("click",function(e){if(e.target===overlay)closeMifrm();});}document.addEventListener("keydown",function(e){if(e.key==="Escape"&&overlay&&overlay.classList.contains("active"))closeMifrm();});});function vbGetState(){try{return JSON.parse(localStorage.getItem(VB_NOTIF_KEY))||{};}catch(e){return{};}}
function vbSetState(s){try{localStorage.setItem(VB_NOTIF_KEY,JSON.stringify(s));}catch(e){}}
function vbCleanExpired(items){var now=Date.now();return(items||[]).filter(function(it){return(now-it.ts)<VB_TTL;});}
function vbRenderNotifs(){var bellEl=document.getElementById("vbNotif");var dotEl=document.getElementById("vbNotifDot");var listEl=document.getElementById("vbNotifList");if(!bellEl)return;var state=vbGetState();var items=vbCleanExpired(state.items||[]);var dismissed=!!state.dismissed;var unread=dismissed?0:items.length;bellEl.classList.toggle("has-unread",unread>0);if(dotEl)dotEl.textContent=unread>0?(unread>9?"9+":String(unread)):"";if(!listEl)return;if(!items.length||dismissed){listEl.innerHTML='<div class="vb-notif-empty"><i data-lucide="circle-check"></i><br/>Yeni bildirim yok.</div>';vbIcons(listEl);return;}
var html="";items.forEach(function(it){var isReply=it.kind==="reply";var kCls=isReply?" reply":"";var kIco=isReply?"reply":"pen-line";var kLbl=isReply?"YENİ CEVAP":"YENİ KONU";html+='<a class="vb-notif-item" href="'+(it.link||"/")+'">'
+'<span class="vb-notif-kind'+kCls+'">'
+'<i data-lucide="'+kIco+'" aria-hidden="true"></i> '
+kLbl+'</span>'
+'<span class="vb-notif-title">'+(it.title||"—")+'</span>'
+'<span class="vb-notif-sub">'+(it.sub||"")+'</span>'
+'</a>';});listEl.innerHTML=html;vbIcons(listEl);}
function vbToggleNotif(){var bellEl=document.getElementById("vbNotif");var btnEl=document.getElementById("vbNotifBell");if(!bellEl)return;var isOpen=bellEl.classList.toggle("open");if(btnEl)btnEl.setAttribute("aria-expanded",isOpen?"true":"false");}
function vbDismissAll(){var state=vbGetState();state.dismissed=true;vbSetState(state);vbRenderNotifs();var bellEl=document.getElementById("vbNotif");var btnEl=document.getElementById("vbNotifBell");if(bellEl)bellEl.classList.remove("open");if(btnEl)btnEl.setAttribute("aria-expanded","false");}
function vbCheckActivity(){var p1=cachedFetch("/feeds/posts/summary?alt=json&orderby=published&max-results="+MFG("notif.topicsCount",20));var p2=cachedFetch("/feeds/comments/default?alt=json&max-results="+MFG("notif.repliesCount",20));Promise.all([p1,p2]).then(function(res){var posts=(res[0]&&res[0].feed&&res[0].feed.entry)||[];var comments=(res[1]&&res[1].feed&&res[1].feed.entry)||[];var state=vbGetState();if(!state.seenTopic&&!state.seenComment){state.seenTopic=posts.length?posts[0].published.$t:"";state.seenComment=comments.length?comments[0].published.$t:"";state.items=[];state.dismissed=false;vbSetState(state);vbRenderNotifs();return;}
var existing=vbCleanExpired(state.items||[]);var existingIds=existing.map(function(it){return it.id;});var newItems=[];posts.forEach(function(p){var pub=tsOf(p.published.$t),seen=tsOf(state.seenTopic||"");if(seen&&pub>seen){var link=getAltLink(p);var id="t_"+(p.id?p.id.$t:pub);if(existingIds.indexOf(id)===-1){newItems.push({id:id,kind:"topic",ts:Date.now(),title:safeText(p.title?p.title.$t:"Yeni Konu"),sub:"Yazan: "+safeText(getAuthorName(p))+" · "+formatDate(p.published.$t),link:link?link.href:"/"});}}});comments.forEach(function(c){var pub=tsOf(c.published.$t),seen=tsOf(state.seenComment||"");if(seen&&pub>seen){var link=getAltLink(c);var id="c_"+(c.id?c.id.$t:pub);if(existingIds.indexOf(id)===-1){var postTitle=(c.title&&c.title.$t)?c.title.$t:(link&&link.title?link.title:"Bir konu");newItems.push({id:id,kind:"reply",ts:Date.now(),title:safeText(postTitle),sub:safeText(getAuthorName(c))+" cevap yazdı · "+formatDate(c.published.$t),link:link?link.href:"/"});}}});if(posts.length)state.seenTopic=posts[0].published.$t;if(comments.length)state.seenComment=comments[0].published.$t;state.items=newItems.concat(existing).slice(0,MFG("notif.maxItems",50));if(newItems.length){state.dismissed=false;var first=newItems[0];vbToast(first.kind==="reply"?"Yeni Cevap Geldi!":"Yeni Konu Açıldı!",first.title.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"'));}
vbSetState(state);vbRenderNotifs();});}
function renderVbTopics(shown){var target=document.getElementById("vb-last-posts-target");if(!target||!_vbAllPosts.length)return;var slice=_vbAllPosts.slice(0,shown);var html="";slice.forEach(function(p){var avatarHtml=p.avatar?'<img src="'+p.avatar+'" alt="'+safeText(p.author)+'" loading="lazy" width="32" height="32"/>':'<i data-lucide="user" aria-hidden="true"></i>';var catHtml=p.category?'<span class="vb-cat-badge"><i data-lucide="'+getCategoryIcon(p.category)+'" aria-hidden="true"></i>'+safeText(p.category)+'</span>':'';html+='<div class="hamdi-forum-row">'
+'<div class="hamdi-avatar-holder" aria-hidden="true">'+avatarHtml
+'<div class="hamdi-status-dot"></div></div>'
+'<div class="hamdi-main-info">'
+'<div class="hamdi-title"><a href="'+p.link+'">'+p.title+'</a></div>'
+'<div class="hamdi-meta">'+catHtml
+'<i data-lucide="user" aria-hidden="true" style="margin-right:3px"></i>'
+'<span class="hamdi-author">'+safeText(p.author)+'</span> &middot; '+p.date+'</div>'
+'</div>'
+'<div class="hamdi-replies-zone"><i data-lucide="message-circle" aria-hidden="true" style="margin-right:3px"></i>'+p.replies+'</div>'
+'<div class="hamdi-arrow-zone" aria-hidden="true"><i data-lucide="chevron-right"></i></div>'
+'</div>';});target.innerHTML=html;vbIcons(target);var moreWrap=document.getElementById("vb-topics-more");if(moreWrap)moreWrap.style.display=(shown<_vbAllPosts.length)?"block":"none";}
function loadMoreTopics(){var prev=_vbShown;_vbShown=Math.min(_vbShown+MFG("home.loadMoreStep",10),_vbAllPosts.length);renderVbTopics(_vbShown);var target=document.getElementById("vb-last-posts-target");if(target){var rows=target.querySelectorAll(".hamdi-forum-row");var nextRow=rows[prev];if(nextRow&&nextRow.scrollIntoView){nextRow.scrollIntoView({behavior:"smooth",block:"start"});}else{target.scrollTo({top:target.scrollHeight,behavior:"smooth"});}}}
function fetchBloggerViews(){var viewsEl=document.getElementById("stat-total-views");if(!viewsEl)return;function tryRead(){var span=document.getElementById("Stats1_totalCount");if(!span)return false;var raw=(span.textContent||span.innerText||"").trim();var num=raw.replace(/[^0-9]/g,"");if(num.length>0){viewsEl.textContent=Number(num).toLocaleString("tr-TR");return true;}
return false;}
if(tryRead())return;var span=document.getElementById("Stats1_totalCount");var mo=null;if(span&&typeof MutationObserver!=="undefined"){mo=new MutationObserver(function(){if(tryRead()){mo.disconnect();clearInterval(iv);}});mo.observe(span,{childList:true,characterData:true,subtree:true});}
var att=0;var iv=setInterval(function(){att++;if(tryRead()){clearInterval(iv);if(mo)mo.disconnect();return;}
if(att>=40){clearInterval(iv);if(mo)mo.disconnect();if(!viewsEl.textContent||viewsEl.textContent==="—"){viewsEl.textContent="—";}}},300);}
function fetchBloggerViewsWeek(){var onlineEl=document.getElementById("stat-online-count");if(!onlineEl)return;Promise.all([cachedFetch("/feeds/posts/summary?alt=json&max-results=500"),cachedFetch("/feeds/comments/default?alt=json&max-results=500")]).then(function(res){var authors={};((res[0]&&res[0].feed&&res[0].feed.entry)||[]).forEach(function(e){var n=getAuthorName(e);if(n&&n!=="Misafir")authors[n]=1;});((res[1]&&res[1].feed&&res[1].feed.entry)||[]).forEach(function(e){var n=getAuthorName(e);if(n&&n!=="Misafir")authors[n]=1;});var c=Object.keys(authors).length;onlineEl.textContent=c.toLocaleString("tr-TR")+" Üye";}).catch(function(){onlineEl.textContent="—";});}
function loadPostbitStats(){var joinSpan=document.querySelector(".pb-join-val");var topicsSpan=document.querySelector(".pb-topics-val");var msgsSpan=document.querySelector(".pb-msgs-val");var citySpan=document.querySelector(".pb-city-val");var followSpan=document.querySelector(".pb-follow-val");if(!joinSpan&&!topicsSpan&&!msgsSpan)return;var authorNameEl=document.querySelector(".xf-uname span[itemprop='name']");var authorName=authorNameEl?authorNameEl.textContent.trim():"";if(!authorName||authorName==="Misafir"){if(joinSpan)joinSpan.textContent="Misafir";if(topicsSpan)topicsSpan.textContent="—";if(msgsSpan)msgsSpan.textContent="—";return;}
cachedFetch("/feeds/posts/summary?alt=json&max-results=500").then(function(data){var entries=(data&&data.feed&&data.feed.entry)||[];var oldest=null;var topics=0;var totalMsgs=0;var profileUri="";entries.forEach(function(e){var name="";try{name=cleanAuthor(e.author[0].name.$t);}catch(ex){}
if(name!==authorName)return;topics++;var pub=e.published?e.published.$t:null;if(pub&&(!oldest||tsOf(pub)<tsOf(oldest)))oldest=pub;var cmt=0;try{cmt=parseInt(e["thr$total"].$t,10)||0;}catch(ex){}
totalMsgs+=cmt;if(!profileUri){try{profileUri=e.author[0].uri.$t;}catch(ex){}}});if(joinSpan)joinSpan.textContent=oldest?formatDateShort(oldest):"—";if(topicsSpan)topicsSpan.textContent=topics>0?topics:"—";if(msgsSpan)msgsSpan.textContent=totalMsgs;buildAvatarCache(entries);applyAvatarCache();if(profileUri&&citySpan){loadProfileLocation(profileUri,citySpan,followSpan);}});}
function loadProfileLocation(profileUri,cityEl,followEl){var m=profileUri.match(/\/profile\/(\d+)/);if(!m)return;var uid=m[1];fetch("https://www.blogger.com/feeds/"+uid+"/blogs?alt=json&max-results=0").then(function(r){return r.ok?r.json():null;}).catch(function(){return null;}).then(function(d){if(!d||!d.feed)return;var total=0;try{total=parseInt(d.feed["openSearch$totalResults"].$t,10);}catch(ex){}
if(followEl&&total>0)followEl.textContent=total;var loc="";try{loc=d.feed.author[0]["gd$extendedProperty"].find(function(p){return p.name==="user.location";}).value;}catch(ex){}
if(cityEl&&loc)cityEl.textContent=loc;});}
function mifrmFillCatLastPost(label,lBox,iconEl){var u="/feeds/posts/summary/-/"+encodeURIComponent(label)+"?alt=json&orderby=published&max-results=1";cachedFetch(u).then(function(d){var ents=(d&&d.feed&&d.feed.entry)||[];if(!ents.length){lBox.innerHTML='<em style="color:var(--meta);">Bu kategoride henüz konu yok.</em>';return;}var e=ents[0];var link=getAltLink(e);var isNew=e.published&&(Date.now()-tsOf(e.published.$t))<259200000;if(iconEl)vbSetIcon(iconEl,getCategoryIcon(label));lBox.innerHTML='Son Konu: <a class="cat-last-title" href="'+(link?link.href:"#")+'">'+safeText(e.title?e.title.$t:"")+'</a>'+'<div class="cat-last-meta">Gönderen: <strong>'+safeText(getAuthorName(e))+'</strong> — '+formatDate(e.published?e.published.$t:"")+'</div>';});}
function loadForumSystem(){var target=document.getElementById("vb-last-posts-target");if(!target)return;var p1=cachedFetch("/feeds/posts/summary?alt=json&max-results=500");var p2=cachedFetch("/feeds/comments/default?alt=json&max-results=1");Promise.all([p1,p2]).then(function(res){var feed=res[0]&&res[0].feed;var cmtFeed=res[1]&&res[1].feed;var entries=(feed&&feed.entry)||[];var total=feed&&feed["openSearch$totalResults"]?parseInt(feed["openSearch$totalResults"].$t,10):entries.length;var postCountEl=document.getElementById("stat-total-posts");if(postCountEl)postCountEl.textContent=total.toLocaleString("tr-TR");fetchBloggerViewsWeek();if(!entries.length){target.innerHTML='<div style="padding:24px;text-align:center;color:var(--meta);">'
+'<i data-lucide="inbox" style="font-size:22px;display:block;margin-bottom:7px" aria-hidden="true"></i>'
+'Henüz forum konusu yok.</div>';vbIcons(target);}else{var catMap={};_vbAllPosts=[];entries.forEach(function(e){var link=getAltLink(e);var author=getAuthorName(e);var avatar=getAuthorImg(e);var item={title:safeText(e.title?e.title.$t:""),link:link?link.href:"#",author:author,avatar:avatar,date:formatDate(e.published?e.published.$t:""),published:e.published?e.published.$t:"",replies:e["thr$total"]?String(e["thr$total"].$t):"0",category:(e.category&&e.category.length)?e.category[0].term:""};_vbAllPosts.push(item);if(e.category){e.category.forEach(function(cat){if(!catMap[cat.term])catMap[cat.term]=item;});}});var catSel=document.getElementById("mifrm-category");if(catSel){var allCats={};Object.keys(catMap).forEach(function(k){allCats[k]=1;});if(feed&&feed.category)feed.category.forEach(function(c){if(c.term)allCats[c.term]=1;});var opts='<option value="">Kategori Seçin</option>';Object.keys(allCats).sort(function(a,b){return a.localeCompare(b,"tr");}).forEach(function(n){opts+='<option value="'+safeText(n)+'">'+safeText(n)+'</option>';});catSel.innerHTML=opts;}
_vbShown=MFG("home.topicsCount",10);renderVbTopics(_vbShown);var lastTopicEl=document.getElementById("stat-last-topic");if(lastTopicEl&&entries[0]){var lnk=getAltLink(entries[0]);lastTopicEl.innerHTML='<strong>'+safeText(getAuthorName(entries[0]))+'</strong> — '
+'<a href="'+(lnk?lnk.href:"#")+'" style="color:var(--lnk);">'
+safeText(entries[0].title?entries[0].title.$t:"")+'</a>';}
document.querySelectorAll(".class-target-label-box").forEach(function(box){var label=box.getAttribute("data-label");var lBox=box.querySelector(".cat-last-post-box");if(!lBox)return;var last=catMap[label];var iconEl=document.querySelector('.category-icon-wrapper[data-label="'+label+'"]');var isNew=last&&last.published&&(Date.now()-tsOf(last.published))<259200000;if(iconEl)vbSetIcon(iconEl,getCategoryIcon(label));if(last){lBox.innerHTML='Son Konu: <a class="cat-last-title" href="'+last.link+'">'+last.title+'</a>'
+'<div class="cat-last-meta">Gönderen: <strong>'+safeText(last.author)+'</strong> — '+last.date+'</div>';}else{lBox.innerHTML='<em style="color:var(--meta);">Yükleniyor...</em>';mifrmFillCatLastPost(label,lBox,iconEl);}});}
if(cmtFeed){var cmtTotal=cmtFeed["openSearch$totalResults"]?parseInt(cmtFeed["openSearch$totalResults"].$t,10):0;var cmtEl=document.getElementById("stat-total-comments");if(cmtEl)cmtEl.textContent=cmtTotal.toLocaleString("tr-TR");var lastReplyEl=document.getElementById("stat-last-reply");var cmtEntries=cmtFeed.entry||[];if(lastReplyEl&&cmtEntries.length){var c=cmtEntries[0];var clnk=getAltLink(c);var postTitle=(c.title&&c.title.$t)?c.title.$t:"Bir konu";var body=((c.content&&c.content.$t)||(c.summary&&c.summary.$t)||"").replace(/<\/?[^>]+>/g,"").trim();if(body.length>55)body=body.substring(0,55)+"...";lastReplyEl.innerHTML='<strong>'+safeText(getAuthorName(c))+'</strong>'
+' — <a href="'+(clnk?clnk.href:"#")+'" style="color:var(--lnk);">'+safeText(postTitle)+'</a>'
+(body?': <em>"'+safeText(body)+'"</em>':'');}}
fetchBloggerViews();});}
function switchVbTab(tab){document.querySelectorAll(".vb-tab").forEach(function(btn){btn.classList.toggle("active",btn.getAttribute("data-tab")===tab);});document.querySelectorAll(".vb-tab-pane").forEach(function(pane){pane.classList.toggle("active",pane.id==="vb-pane-"+tab);});if(tab==="comments"){var target=document.getElementById("vb-comments-target");if(target&&!target.getAttribute("data-loaded")){loadRecentComments();}}}
function renderCommentRows(shown){var target=document.getElementById("vb-comments-target");if(!target)return;if(!_cmtTopics.length)return;var slice=_cmtTopics.slice(0,shown);var html="";slice.forEach(function(t){var title=t.title;if(title.length>72)title=title.substring(0,72)+"…";var catName="";var replyCount="";if(_vbAllPosts.length){for(var j=0;j<_vbAllPosts.length;j++){var pLink=(_vbAllPosts[j].link||"").split("#")[0];if(pLink&&t.postUrl.indexOf(pLink)!==-1){catName=_vbAllPosts[j].category||"";replyCount=(_vbAllPosts[j].replies!==undefined)?String(_vbAllPosts[j].replies):"";break;}}}
var avtHtml=t.lastAvatar?'<img src="'+t.lastAvatar+'" alt="'+safeText(t.lastAuthor)+'" loading="lazy" width="32" height="32"/>':'<i data-lucide="user" aria-hidden="true"></i>';var catHtml=catName?'<span class="vb-cat-badge"><i data-lucide="'+getCategoryIcon(catName)+'" aria-hidden="true"></i>'+safeText(catName)+'</span>':'';html+='<div class="hamdi-forum-row">'
+'<div class="hamdi-avatar-holder" aria-hidden="true">'+avtHtml
+'<div class="hamdi-status-dot"></div></div>'
+'<div class="hamdi-main-info">'
+'<div class="hamdi-title">'
+'<a href="'+t.commentLink+'">'+safeText(title)+'</a>'
+'</div>'
+'<div class="hamdi-meta">'+catHtml
+'<i data-lucide="reply" aria-hidden="true" style="margin-right:3px;font-size:10px;"></i>'
+'<span class="hamdi-author">'+safeText(t.lastAuthor)+'</span>'
+' &middot; '+t.date
+'</div>'
+'</div>'
+'<div class="hamdi-replies-zone">'
+(replyCount!==""?'<i data-lucide="message-circle" aria-hidden="true" style="margin-right:3px"></i>'+replyCount:'')
+'</div>'
+'<div class="hamdi-arrow-zone" aria-hidden="true"><i data-lucide="chevron-right"></i></div>'
+'</div>';});target.innerHTML=html;vbIcons(target);var moreWrap=document.getElementById("vb-comments-more");if(moreWrap)moreWrap.style.display=(shown<_cmtTopics.length)?"block":"none";}
function loadMoreComments(){var prev=_cmtShown;_cmtShown=Math.min(_cmtShown+MFG("home.loadMoreStep",10),_cmtTopics.length);renderCommentRows(_cmtShown);var target=document.getElementById("vb-comments-target");if(target){var rows=target.querySelectorAll(".hamdi-forum-row");var nextRow=rows[prev];if(nextRow&&nextRow.scrollIntoView){nextRow.scrollIntoView({behavior:"smooth",block:"start"});}else{target.scrollTo({top:target.scrollHeight,behavior:"smooth"});}}}
function loadRecentComments(){var target=document.getElementById("vb-comments-target");if(!target)return;target.setAttribute("data-loaded","1");target.innerHTML='<div style="padding:20px;text-align:center;color:var(--meta);">'
+'<i class="vb-spin" data-lucide="loader-circle" style="margin-right:7px" aria-hidden="true"></i>Yükleniyor...</div>';vbIcons(target);cachedFetch("/feeds/comments/default?alt=json&max-results=60").then(function(data){_cmtAllEntries=(data&&data.feed&&data.feed.entry)||[];if(!_cmtAllEntries.length){target.innerHTML='<div style="padding:24px;text-align:center;color:var(--meta);">'
+'<i data-lucide="message-circle-off" style="font-size:22px;display:block;margin-bottom:7px" aria-hidden="true"></i>'
+'Henüz cevap yok.</div>';vbIcons(target);return;}
var seen={};_cmtTopics=[];_cmtAllEntries.forEach(function(e){var link="";try{for(var i=0;i<e.link.length;i++){if(e.link[i].rel==="alternate"){link=e.link[i].href;break;}}}catch(ex){}
var postUrl=link.split("#")[0];if(!postUrl||seen[postUrl])return;seen[postUrl]=true;_cmtTopics.push({postUrl:postUrl,commentLink:link,title:(e.title&&e.title.$t)?e.title.$t:"—",lastAuthor:getAuthorName(e),lastAvatar:getAuthorImg(e),date:formatDate(e.published?e.published.$t:"")});});_cmtShown=MFG("home.repliesCount",10);renderCommentRows(_cmtShown);});}
function triggerVbulletinReply(){var area=document.getElementById("vb-toggle-comment-area");if(!area)return;if(area.classList.contains("form-active")){area.classList.remove("form-active");}else{area.classList.add("form-active");vbToast("Cevap Paneli Açıldı","Forum kurallarına uygun bir cevap yazın.");setTimeout(function(){area.scrollIntoView({behavior:"smooth",block:"center"});},150);}}
document.addEventListener("DOMContentLoaded",function(){document.addEventListener("click",function(e){var bellEl=document.getElementById("vbNotif");if(bellEl&&bellEl.classList.contains("open")&&!bellEl.contains(e.target)){bellEl.classList.remove("open");var btn=document.getElementById("vbNotifBell");if(btn)btn.setAttribute("aria-expanded","false");}});vbCheckActivity();_vbTimer=setInterval(vbCheckActivity,60000);vbRenderNotifs();if(document.getElementById("vb-last-posts-target")){loadForumSystem();}
loadPageAvatars();if(document.querySelector(".pb-topics-val")){loadPostbitStats();}if(!document.getElementById("vb-last-posts-target")){var _catSel=document.getElementById("mifrm-category");if(_catSel){cachedFetch("/feeds/posts/summary?alt=json&max-results=500").then(function(d){var fd=(d&&d.feed)||{};var ents=fd.entry||[];var cats={};ents.forEach(function(e){if(e.category){e.category.forEach(function(c){if(c.term)cats[c.term]=1;});}});if(fd.category)fd.category.forEach(function(c){if(c.term)cats[c.term]=1;});var keys=Object.keys(cats).sort(function(a,b){return a.localeCompare(b,"tr");});if(!keys.length)return;var opts='<option value="">Kategori Seçin</option>';keys.forEach(function(n){opts+='<option value="'+safeText(n)+'">'+safeText(n)+'</option>';});_catSel.innerHTML=opts;});}}applyCategoryIcons();injectReadingTime();if(document.getElementById("vb-404-recent")){load404RecentTopics();}});var MIFRM_USER=null,MIFRM_CATS_LOADED=false;function mifrmEsc(s){var d=document.createElement("div");d.textContent=(s==null?"":String(s));return d.innerHTML;}
function mifrmDecodeJwt(t){try{var p=t.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");var j=decodeURIComponent(atob(p).split("").map(function(c){return"%"+("00"+c.charCodeAt(0).toString(16)).slice(-2);}).join(""));return JSON.parse(j);}catch(e){return null;}}
function mifrmLoadUser(){try{var s=localStorage.getItem("mifrm_user");if(s)MIFRM_USER=JSON.parse(s);}catch(e){MIFRM_USER=null;}}
function mifrmSaveUser(u){MIFRM_USER=u;try{localStorage.setItem("mifrm_user",JSON.stringify(u));}catch(e){}mifrmRenderUser();if(typeof setMifrmStatus==="function")setMifrmStatus("");}
function mifrmGoogleCallback(resp){var data=mifrmDecodeJwt(resp.credential);if(!data){if(typeof setMifrmStatus==="function")setMifrmStatus("Giris dogrulanamadi, tekrar deneyin.","error");return;}mifrmSaveUser({name:data.name||"",email:data.email||"",picture:data.picture||""});}
function mifrmLogout(){MIFRM_USER=null;try{localStorage.removeItem("mifrm_user");}catch(e){}if(window.google&&google.accounts&&google.accounts.id){try{google.accounts.id.disableAutoSelect();}catch(e){}}mifrmRenderUser();}
function mifrmInitGoogleBtn(){var cid=(typeof MFG==="function"?MFG("signup.clientId",""):"");var holder=document.getElementById("mifrm-gbtn");if(!holder)return;if(!cid||cid.indexOf("YOUR_CLIENT_ID")!==-1){holder.innerHTML='<span style="color:var(--red);font-size:12px">Yonetici: Google Istemci Kimligi (Client ID) henuz ayarlanmamis.</span>';return;}if(!(window.google&&google.accounts&&google.accounts.id))return;try{google.accounts.id.initialize({client_id:cid,callback:mifrmGoogleCallback,auto_select:false});holder.innerHTML="";google.accounts.id.renderButton(holder,{theme:"filled_blue",size:"large",text:"signin_with",shape:"pill",locale:"tr",width:260});}catch(e){}}
function mifrmRenderUser(){var loginBox=document.getElementById("mifrm-login"),formBox=document.getElementById("mifrm-form"),ub=document.getElementById("mifrm-user"),av=document.getElementById("hamdi-avatar");if(MIFRM_USER){if(loginBox)loginBox.style.display="none";if(formBox)formBox.style.display="block";if(ub){ub.innerHTML='<img src="'+mifrmEsc(MIFRM_USER.picture)+'" alt="" referrerpolicy="no-referrer"/><span><span class="mifrm-uname">'+mifrmEsc(MIFRM_USER.name)+'</span><br/><span class="mifrm-umail">'+mifrmEsc(MIFRM_USER.email)+'</span></span><button type="button" class="mifrm-logout" onclick="mifrmLogout()">Cikis</button>';ub.style.display="flex";}if(av){av.innerHTML='<img src="'+mifrmEsc(MIFRM_USER.picture)+'" alt="Profil" referrerpolicy="no-referrer"/>';av.classList.add("show");av.setAttribute("title",MIFRM_USER.name||"");}}else{if(loginBox)loginBox.style.display="block";if(formBox)formBox.style.display="none";if(ub)ub.style.display="none";if(av){av.innerHTML="";av.classList.remove("show");}mifrmInitGoogleBtn();}}
function mifrmLoadCategories(){var sel=document.getElementById("mifrm-category");if(!sel)return;var done=function(html){sel.innerHTML=html;};var url="/feeds/posts/summary?alt=json&max-results=500";var go=(typeof cachedFetch==="function")?cachedFetch(url):fetch(url).then(function(r){return r.json();});go.then(function(d){var fd=(d&&d.feed)||{},ents=fd.entry||[],cats={};ents.forEach(function(e){if(e.category)e.category.forEach(function(c){if(c.term)cats[c.term]=1;});});if(fd.category)fd.category.forEach(function(c){if(c.term)cats[c.term]=1;});var keys=Object.keys(cats).sort(function(a,b){return a.localeCompare(b,"tr");});if(!keys.length){done('<option value="">(Kategori bulunamadi)</option>');return;}var opts='<option value="">Kategori secin...</option>';keys.forEach(function(n){opts+='<option value="'+mifrmEsc(n)+'">'+mifrmEsc(n)+'</option>';});done(opts);}).catch(function(){done('<option value="">(Kategoriler yuklenemedi)</option>');});}
function submitQuickTopic(){if(!MIFRM_USER){setMifrmStatus("Once Google ile giris yapin.","error");return;}var tEl=document.getElementById("mifrm-title"),cEl=document.getElementById("mifrm-category"),bEl=document.getElementById("mifrm-content"),btn=document.getElementById("mifrmSendBtn");var title=tEl?tEl.value.trim():"",cat=cEl?cEl.value.trim():"",body=bEl?bEl.value.trim():"";if(!title){setMifrmStatus("Konu basligi bos olamaz!","error");if(tEl)tEl.focus();return;}if(!cat){setMifrmStatus("Lutfen bir kategori secin!","error");if(cEl)cEl.focus();return;}if(body.length<10){setMifrmStatus("Konu icerigi en az 10 karakter olmali!","error");if(bEl)bEl.focus();return;}
var to=MFG("signup.bloggerMail","hamdiuludag.news@blogger.com");var adminNote="\n\n----------------------------------------\n[YONETICI NOTU \u2014 yayinlamadan once bu bolumu silin]\nKategori: "+cat+"\nGonderen: "+(MIFRM_USER.name||"")+" <"+(MIFRM_USER.email||"")+">\n----------------------------------------";var mailBody=body+adminNote;var mailtoUrl="mailto:"+encodeURIComponent(to)+"?subject="+encodeURIComponent(title)+"&body="+encodeURIComponent(mailBody);if(btn)btn.disabled=true;setMifrmStatus("E-posta uygulamaniz aciliyor. Acilan ekranda 'Gonder'e basin; konu Blogger'da TASLAK olarak kaydedilir.","success");if(tEl)tEl.value="";if(bEl)bEl.value="";if(cEl)cEl.value="";window.location.href=mailtoUrl;if(btn)btn.disabled=false;setTimeout(function(){closeMifrm();setMifrmStatus("");},4200);}
window.openMifrm=function(){var el=document.getElementById("mifrm-overlay");if(el)el.classList.add("active");mifrmRenderUser();if(!MIFRM_CATS_LOADED){MIFRM_CATS_LOADED=true;mifrmLoadCategories();}};window.onGoogleLibraryLoad=function(){mifrmRenderUser();};document.addEventListener("DOMContentLoaded",function(){mifrmLoadUser();mifrmRenderUser();});function vbIcons(root){try{if(window.lucide&&lucide.createIcons)lucide.createIcons(root?{root:root}:undefined);}catch(e){}}
function vbSetIcon(el,name){if(!el)return;el.innerHTML='<i data-lucide="'+(name||'folder')+'"></i>';vbIcons(el);}
function vbNormTr(s){return String(s||'').toLocaleLowerCase('tr-TR').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ş/g,'s').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,' ').trim();}
var VB_CAT_ICON_MAP=[["duyuru|announcement|bildiri","megaphone"],["kural|yonetmelik|mevzuat","scale"],["yazilim|kodlama|programlama|developer|gelistir","code"],["oyun|game|e-spor|espor","gamepad-2"],["bilgisayar|donanim|hardware|pc|islemci","cpu"],["telefon|mobil|akilli telefon|phone|tablet|iphone|android|samsung|xiaomi|ios","smartphone"],["internet|network|wifi|siber","wifi"],["teknoloji|technology|tech|elektronik","cpu"],["spor|futbol|basketbol|voleybol|fitness|antrenman|kosu","dumbbell"],["saglik|health|tip|hastalik|doktor|psikoloji","heart-pulse"],["egitim|okul|universite|ders|kurs|ogrenci|akademik","graduation-cap"],["muzik|music|sarki|album|konser","music"],["film|dizi|sinema|movie|belgesel","clapperboard"],["sanat|art|cizim|resim|tasarim|illustrasyon","palette"],["yemek|mutfak|tarif|food|recipe|restoran","utensils"],["seyahat|gezi|tatil|travel|turizm","plane"],["otomobil|araba|arac|car|motor|motosiklet","car"],["finans|ekonomi|para|borsa|yatirim|kripto|banka","banknote"],["emlak|konut|gayrimenkul|daire","house"],["moda|giyim|kiyafet|fashion|stil","shirt"],["kitap|roman|edebiyat|book|yazar|siir","book-open"],["bilim|science|fizik|kimya|biyoloji|uzay|astronomi","flask-conical"],["doga|cevre|nature|bitki|iklim","leaf"],["hayvan|pet|evcil|kedi|kopek","paw-print"],["guvenlik|security|antivirus|hack","shield"],["soru|yardim|help|sss|faq|destek","circle-help"],["oneri|geri bildirim|feedback|fikir|istek","lightbulb"],["sikayet|complaint|sorun|problem","flag"],["tanitim|reklam|promotion|kampanya","megaphone"],["is|kariyer|job|career|meslek|ilan","briefcase"],["fotograf|photo|kamera","camera"],["video|yayin|canli yayin","video"],["sosyal medya|social|paylasim","share-2"],["alisveris|market|shopping|indirim|urun","shopping-cart"],["haber|gundem|news|guncel","newspaper"],["yapay zeka|yapayzeka|chatgpt|chatbot|copilot|gemini yapay zeka|llm|makine ogrenmesi|derin ogrenme","brain-circuit"],["google|yandex|bing|duckduckgo|arama motoru|search engine","search"],["phpbb|joomla|vbulletin|wordpress|blogger|discourse|mybb|xenforo|drupal|invision|ipb|simple machines|smf","layout-template"],["ruya|ruya tabiri|ruya tabirleri|dream","moon-star"],["sunucu|hosting|barindirma|server|vps|domain|alan adi","server"],["web sitesi|website|web tasarimi|webmaster","globe"],["genel|general|sohbet|muhabbet|chat|misc","message-square"]];
function getCategoryIcon(name){var tokens=vbNormTr(name).split(' ').filter(Boolean);var joined=' '+tokens.join(' ')+' ';for(var i=0;i<VB_CAT_ICON_MAP.length;i++){var keys=VB_CAT_ICON_MAP[i][0].split('|');for(var k=0;k<keys.length;k++){var kw=vbNormTr(keys[k]);if(!kw)continue;if(kw.indexOf(' ')!==-1){if(joined.indexOf(' '+kw+' ')!==-1)return VB_CAT_ICON_MAP[i][1];continue;}for(var t=0;t<tokens.length;t++){if(tokens[t]===kw||tokens[t].indexOf(kw)===0)return VB_CAT_ICON_MAP[i][1];}}}return'folder';}
function applyCategoryIcons(){document.querySelectorAll('.category-icon-wrapper[data-label]').forEach(function(el){vbSetIcon(el,getCategoryIcon(el.getAttribute('data-label')));});}
function load404RecentTopics(){var target=document.getElementById('vb-404-recent');if(!target)return;cachedFetch('/feeds/posts/summary?alt=json&max-results=10').then(function(data){var entries=(data&&data.feed&&data.feed.entry)||[];if(!entries.length){target.innerHTML='<div style="padding:18px;text-align:center;color:var(--meta);">Henüz forum konusu yok.</div>';return;}
var html='';entries.forEach(function(e){var link=getAltLink(e);var author=getAuthorName(e);var avatar=getAuthorImg(e);var avtHtml=avatar?'<img src="'+avatar+'" alt="'+safeText(author)+'" loading="lazy" width="32" height="32"/>':'<i data-lucide="user" aria-hidden="true"></i>';var cat=(e.category&&e.category.length)?e.category[0].term:'';var catHtml=cat?'<span class="vb-cat-badge"><i data-lucide="'+getCategoryIcon(cat)+'" aria-hidden="true"></i>'+safeText(cat)+'</span>':'';html+='<div class="hamdi-forum-row">'
+'<div class="hamdi-avatar-holder" aria-hidden="true">'+avtHtml
+'<div class="hamdi-status-dot"></div></div>'
+'<div class="hamdi-main-info">'
+'<div class="hamdi-title"><a href="'+(link?link.href:'#')+'">'+safeText(e.title?e.title.$t:'')+'</a></div>'
+'<div class="hamdi-meta">'+catHtml
+'<i data-lucide="user" aria-hidden="true" style="margin-right:3px"></i>'
+'<span class="hamdi-author">'+safeText(author)+'</span> &middot; '+formatDate(e.published?e.published.$t:'')+'</div>'
+'</div>'
+'<div class="hamdi-replies-zone"><i data-lucide="message-circle" aria-hidden="true" style="margin-right:3px"></i>'+(e['thr$total']?e['thr$total'].$t:'0')+'</div>'
+'<div class="hamdi-arrow-zone" aria-hidden="true"><i data-lucide="chevron-right"></i></div>'
+'</div>';});target.innerHTML=html;vbIcons(target);buildAvatarCache(entries);applyAvatarCache();}).catch(function(){target.innerHTML='<div style="padding:18px;text-align:center;color:var(--meta);">Konular yüklenemedi.</div>';});}
function injectReadingTime(){var body=document.querySelector('.xf-post-body');var head=document.querySelector('.xf-body-head');if(!body||!head||document.querySelector('.vb-read-time'))return;var text=(body.innerText||body.textContent||'').trim();var words=text.split(/\s+/).filter(function(w){return w.length>0;}).length;if(words<50)return;var mins=Math.max(1,Math.ceil(words/200));var label=mins===1?'1 dk okuma':mins+' dk okuma';var badge=document.createElement('span');badge.className='vb-read-time';badge.setAttribute('aria-label','Tahmini okuma süresi: '+label);badge.innerHTML='<i data-lucide="clock" aria-hidden="true"></i>'+label;var controls=head.querySelector('.xf-body-controls');if(controls){head.insertBefore(badge,controls);}else{head.appendChild(badge);}vbIcons(badge);}
(function(){'use strict';var _trCache={};var TSEP='|||S|||';var _origLang='tr';function getTranslatableEls(){var els=[];var title=document.querySelector('.xf-post-title');var body=document.querySelector('.xf-post-body');var comments=document.querySelectorAll('.comment-body');if(title)els.push(title);if(body)els.push(body);for(var i=0;i<comments.length;i++)els.push(comments[i]);return els;}
function getNodes(root){var list=[],w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:function(n){if(!n.nodeValue.trim())return NodeFilter.FILTER_SKIP;var tag=((n.parentElement||{}).tagName||'').toLowerCase();if(tag==='script'||tag==='style'||tag==='code'||tag==='pre')return NodeFilter.FILTER_SKIP;return NodeFilter.FILTER_ACCEPT;}});var n;while((n=w.nextNode()))list.push(n);return list;}
function showLoader(){var body=document.querySelector('.xf-post-body');if(!body||document.getElementById('xf-trans-loading'))return;var el=document.createElement('div');el.id='xf-trans-loading';el.innerHTML='<i class="vb-spin" data-lucide="loader-circle" aria-hidden="true"></i> Çeviriliyor...';body.parentNode.insertBefore(el,body);vbIcons(el);}
function removeLoader(){var el=document.getElementById('xf-trans-loading');if(el&&el.parentNode)el.parentNode.removeChild(el);}
var _gtxQueue=[];var _gtxBusy=false;var _gtxLSPfx='gtx3_';function _gtxLSKey(c,sl,tl){return _gtxLSPfx+sl+'_'+tl+'_'+c.slice(0,80);}
function _gtxLSGet(c,sl,tl){try{var v=localStorage.getItem(_gtxLSKey(c,sl,tl));if(v!==null)return JSON.parse(v);}catch(e){}return null;}
function _gtxLSSave(c,sl,tl,r){try{localStorage.setItem(_gtxLSKey(c,sl,tl),JSON.stringify(r));}catch(e){}}
function _gtxDoFetch(chunk,sl,tl,resolve,retry){retry=retry||0;fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl='+sl+'&tl='+tl+'&dt=t&q='+encodeURIComponent(chunk)).then(function(r){if(r.status===429||r.status===503){if(retry<3){setTimeout(function(){_gtxDoFetch(chunk,sl,tl,resolve,retry+1);},1400*(retry+1));return null;}
resolve(chunk);_gtxBusy=false;_gtxPump();return null;}
return r.ok?r.json():null;}).then(function(d){if(d===null||d===undefined)return;var s='';if(d&&d[0])for(var k=0;k<d[0].length;k++){if(d[0][k]&&d[0][k][0])s+=d[0][k][0];}
_gtxLSSave(chunk,sl,tl,s);resolve(s);_gtxBusy=false;_gtxPump();},function(){resolve(chunk);_gtxBusy=false;_gtxPump();});}
function _gtxPump(){if(_gtxBusy||!_gtxQueue.length)return;_gtxBusy=true;var job=_gtxQueue.shift();setTimeout(function(){_gtxDoFetch(job.chunk,job.sl,job.tl,job.resolve,0);},300);}
function gtxFetch(chunk,sl,tl){var cached=_gtxLSGet(chunk,sl,tl);if(cached!==null)return Promise.resolve(cached);return new Promise(function(resolve){_gtxQueue.push({chunk:chunk,sl:sl,tl:tl,resolve:resolve});_gtxPump();});}
function translateEl(el,sl,tl){if(!el._origHTML)el._origHTML=el.innerHTML;var nodes=getNodes(el);if(!nodes.length)return Promise.resolve('');var rawTexts=nodes.map(function(n){return n.nodeValue;});var chunks=[],cur='';for(var j=0;j<rawTexts.length;j++){var piece=(cur?TSEP:'')+rawTexts[j];if(cur.length+piece.length>4800){chunks.push(cur);cur=rawTexts[j];}
else cur+=piece;}
if(cur)chunks.push(cur);return Promise.all(chunks.map(function(c){return gtxFetch(c,sl,tl);})).then(function(results){el.innerHTML=el._origHTML;var fresh=getNodes(el);var texts=results.join(TSEP).split(TSEP);for(var i=0;i<fresh.length&&i<texts.length;i++){if(texts[i]&&texts[i].trim())fresh[i].nodeValue=texts[i];}
return el.innerHTML;});}
function applyCache(lang){var cached=_trCache[lang];if(!cached)return false;cached.forEach(function(item){if(item.el&&item.el.parentNode)item.el.innerHTML=item.html;});vbReinitPostBody();return true;}
function translateAll(sl,tl,cacheKey){if(applyCache(cacheKey)){removeLoader();return;}
var els=getTranslatableEls();var cacheArr=[];Promise.all(els.map(function(el){return translateEl(el,sl,tl).then(function(html){cacheArr.push({el:el,html:html});});})).then(function(){_trCache[cacheKey]=cacheArr;vbReinitPostBody();removeLoader();}).catch(function(){removeLoader();});}
function setActiveBtn(lang){document.querySelectorAll('.xf-lang-btn').forEach(function(b){b.classList.toggle('active',b.dataset.lang===lang);});}
window.xfSwitchLang=function(lang,btn){setActiveBtn(lang);if(lang===_origLang){getTranslatableEls().forEach(function(el){if(el._origHTML)el.innerHTML=el._origHTML;});vbReinitPostBody();removeLoader();return;}
getTranslatableEls().forEach(function(el){if(!el._origHTML)el._origHTML=el.innerHTML;});if(applyCache(lang)){removeLoader();return;}
showLoader();translateAll(_origLang,lang,lang);};window.xfInitLangSwitcher=function(){var body=document.querySelector('.xf-post-body');if(!body||document.querySelector('.xf-lang-switcher'))return;var sw=document.createElement('div');sw.className='xf-lang-switcher';var b1=document.createElement('button');b1.className='xf-lang-btn active';b1.type='button';b1.dataset.lang='tr';b1.innerHTML='<i data-lucide="flag" aria-hidden="true"></i> Türkçe';b1.onclick=function(){xfSwitchLang('tr',this);};var b2=document.createElement('button');b2.className='xf-lang-btn';b2.type='button';b2.dataset.lang='en';b2.innerHTML='<i data-lucide="languages" aria-hidden="true"></i> İngilizce';b2.onclick=function(){xfSwitchLang('en',this);};sw.appendChild(b1);sw.appendChild(b2);body.parentNode.insertBefore(sw,body);vbIcons(sw);};function autoDetectAndTranslate(){var body=document.querySelector('.xf-post-body');if(!body)return;var sample=(body.innerText||body.textContent||'').trim().slice(0,300);if(!sample)return;fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=tr&dt=t&q='+encodeURIComponent(sample)).then(function(r){if(!r.ok)return null;return r.json();}).then(function(d){if(!d)return;var detected='tr';try{detected=d[2]||'tr';}catch(e){}
_origLang=detected;getTranslatableEls().forEach(function(el){el._origHTML=el.innerHTML;});if(detected!=='tr'){setActiveBtn('tr');showLoader();translateAll(detected,'tr','tr');}else{setActiveBtn('tr');}}).catch(function(){_origLang='tr';setActiveBtn('tr');});}
function extractSummary(text,n){n=n||5;var sents=text.match(/[^.!?]{20,}[.!?]+/g)||[];if(!sents.length)return text.slice(0,500)+'…';var scored=sents.map(function(s,i){var sc=(i<3?3-i:0)+(s.length>60&&s.length<280?1:0);return{s:s,i:i,sc:sc};});scored.sort(function(a,b){return b.sc-a.sc||a.i-b.i;});return scored.slice(0,n).sort(function(a,b){return a.i-b.i;}).map(function(x){return x.s.trim();}).join(' ');}
function closeAiPanel(){var p=document.getElementById('xf-ai-panel');if(p)p.remove();var b=document.getElementById('xf-ai-btn');if(b)b.disabled=false;}
function showAiPanel(html){var old=document.getElementById('xf-ai-panel');if(old)old.remove();var title=document.querySelector('.xf-post-title');if(!title)return;var p=document.createElement('div');p.id='xf-ai-panel';p.className='xf-ai-panel visible';var head=document.createElement('div');head.className='xf-ai-panel-head';head.innerHTML='<i data-lucide="wand-sparkles" aria-hidden="true"></i> Özet';var closeBtn=document.createElement('button');closeBtn.className='xf-ai-panel-close';closeBtn.type='button';closeBtn.innerHTML='<i data-lucide="x" aria-hidden="true"></i>';closeBtn.onclick=closeAiPanel;head.appendChild(closeBtn);var body2=document.createElement('div');body2.className='xf-ai-panel-body';body2.innerHTML=html;p.appendChild(head);p.appendChild(body2);title.insertAdjacentElement('afterend',p);vbIcons(p);}
window.xfAiOzetle=function(btn){btn.disabled=true;var bodyEl=document.querySelector('.xf-post-body');if(!bodyEl){btn.disabled=false;return;}
var text=(bodyEl.innerText||bodyEl.textContent||'').trim();if(!text){btn.disabled=false;return;}
var orig=btn.innerHTML;btn.innerHTML='<i class="vb-spin" data-lucide="loader-circle" aria-hidden="true"></i> Özetleniyor…';vbIcons(btn);setTimeout(function(){showAiPanel(extractSummary(text,5));btn.innerHTML=orig;btn.disabled=false;},250);};document.addEventListener('DOMContentLoaded',function(){window.xfInitLangSwitcher();autoDetectAndTranslate();});var _vbList=[],_vbIdx=0;function _vbBuild(){if(document.getElementById('vbLightbox'))return;var lb=document.createElement('div');lb.id='vbLightbox';lb.setAttribute('role','dialog');lb.setAttribute('aria-modal','true');lb.setAttribute('aria-label','Resim görüntüleyici');lb.innerHTML='<button id="vbLbClose" type="button" title="Kapat (ESC)"><i data-lucide="x"></i></button>'+'<div id="vbLbImgWrap">'+'<button class="vb-lb-nav" id="vbLbPrev" type="button"><i data-lucide="chevron-left"></i></button>'+'<img id="vbLbImg" src="" alt=""/>'+'<button class="vb-lb-nav" id="vbLbNext" type="button"><i data-lucide="chevron-right"></i></button>'+'</div>'+'<div id="vbLbCaption"></div>'+'<div id="vbLbCounter"></div>'+'<div class="vb-lb-thumbrow" id="vbLbThumbs"></div>';document.body.appendChild(lb);vbIcons(lb);document.getElementById('vbLbClose').onclick=vbLbClose;document.getElementById('vbLbPrev').onclick=function(){_vbGo(_vbIdx-1);};document.getElementById('vbLbNext').onclick=function(){_vbGo(_vbIdx+1);};lb.addEventListener('click',function(e){if(e.target===lb)vbLbClose();});document.addEventListener('keydown',function(e){if(!document.getElementById('vbLightbox').classList.contains('vb-lb-open'))return;if(e.key==='Escape')vbLbClose();if(e.key==='ArrowLeft')_vbGo(_vbIdx-1);if(e.key==='ArrowRight')_vbGo(_vbIdx+1);});var tx=0;document.getElementById('vbLbImg').addEventListener('touchstart',function(e){tx=e.touches[0].clientX;},{passive:true});document.getElementById('vbLbImg').addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-tx;if(Math.abs(dx)>48)_vbGo(dx<0?_vbIdx+1:_vbIdx-1);},{passive:true});}
function _vbShow(){var it=_vbList[_vbIdx]||{};var img=document.getElementById('vbLbImg');img.style.animation='none';img.offsetHeight;img.style.animation='vbFdIn .22s ease';img.src=it.src||'';img.alt=it.alt||'';document.getElementById('vbLbCaption').textContent=it.alt||'';var n=_vbList.length;document.getElementById('vbLbCounter').textContent=n>1?(_vbIdx+1)+' / '+n:'';document.getElementById('vbLbPrev').style.display=n>1?'':'none';document.getElementById('vbLbNext').style.display=n>1?'':'none';document.querySelectorAll('.vb-lb-thumb').forEach(function(t,i){t.classList.toggle('vb-on',i===_vbIdx);});var tb=document.getElementById('vbLbThumbs');if(tb&&n>1){var sel=tb.children[_vbIdx];if(sel)sel.scrollIntoView({inline:'nearest',block:'nearest'});}}
function _vbGo(i){_vbIdx=(i+_vbList.length)%_vbList.length;_vbShow();}
function vbLbClose(){var lb=document.getElementById('vbLightbox');if(lb)lb.classList.remove('vb-lb-open');document.body.style.overflow='';}
function _vbOpen(list,idx){_vbList=list;_vbIdx=idx||0;_vbBuild();var tb=document.getElementById('vbLbThumbs');tb.innerHTML='';list.forEach(function(it,i){var t=document.createElement('img');t.src=it.src;t.alt=it.alt||'';t.className='vb-lb-thumb'+(i===_vbIdx?' vb-on':'');t.onclick=function(){_vbGo(i);};tb.appendChild(t);});_vbShow();document.getElementById('vbLightbox').classList.add('vb-lb-open');document.body.style.overflow='hidden';}
function _vbFullSrc(src){return src.replace(/\/s\d+-[a-z]\//,'/s0/').replace(/\/s\d+\//,'/s0/');}
function vbReinitPostBody(){try{vbPostImgInit();}catch(e){}
try{vbExtInit();}catch(e){}}
function vbPostImgInit(){var body=document.querySelector('.xf-post-body');if(!body)return;var imgs=Array.from(body.querySelectorAll('img'));if(!imgs.length)return;imgs.forEach(function(img){var lnk=img.closest('a');if(!img.closest('.vb-wm-wrap')){var wm=document.createElement('div');wm.className='vb-wm-wrap';var wmTarget=lnk||img;wmTarget.parentNode.insertBefore(wm,wmTarget);wm.appendChild(wmTarget);}
if(lnk){if(lnk.getAttribute('href')!==null){lnk.setAttribute('data-vb-href',lnk.getAttribute('href')||'');lnk.removeAttribute('href');}
lnk.style.cursor='zoom-in';}else{img.style.cursor='zoom-in';}});}
document.addEventListener('click',function(e){if(!e.target||!e.target.closest)return;var body=e.target.closest('.xf-post-body');if(!body)return;var img=e.target.closest('img');if(!img||!body.contains(img))return;e.preventDefault();e.stopImmediatePropagation();var imgs=Array.from(body.querySelectorAll('img'));var list=imgs.map(function(im){return{src:_vbFullSrc(im.getAttribute('src')||im.src||''),alt:im.getAttribute('alt')||''};});var idx=imgs.indexOf(img);if(idx<0)idx=0;_vbOpen(list,idx);},true);document.addEventListener('DOMContentLoaded',vbPostImgInit);document.addEventListener('DOMContentLoaded',function(){var path=location.pathname;if(path.indexOf('/search/label/')!==0)return;var raw=path.replace('/search/label/','');var label=decodeURIComponent(raw.replace(/\+/g,' '));if(!label)return;document.querySelectorAll('.hm-bc-current').forEach(function(el){var txt=(el.textContent||'').replace(/\s+/g,'').trim();if(txt.length<2){el.innerHTML='<i aria-hidden="true" data-lucide="folder"></i> '+label;vbIcons(el);}});});function vb404Init(){var sec=document.getElementById('vb404Sec');var bar=document.getElementById('vb404Bar');if(!sec||!bar)return;var adEl=document.getElementById('vb404Ad');var ad=MFG('pageRedirect.adHtml','');if(adEl&&ad)adEl.innerHTML=ad;var total=parseInt(MFG('pageRedirect.countdown',10),10);if(isNaN(total)||total<0)total=10;var target=MFG('pageRedirect.target','/')||'/';var n=total;sec.textContent=n;bar.style.width='100%';if(total<=0){location.href=target;return;}
var iv=setInterval(function(){n--;sec.textContent=n;bar.style.width=((n/total)*100)+'%';if(n<=0){clearInterval(iv);location.href=target;}},1000);}
function vbExtInit(){if(MFG('linkRedirect.enabled',true)===false)return;var body=document.querySelector('.xf-post-body');if(!body)return;var host=location.hostname;var hasExt=false;body.querySelectorAll('a[href]').forEach(function(a){var href=a.getAttribute('href')||'';if(!href||href.charAt(0)==='#'||href.charAt(0)==='/')return;if(a.closest('.vb-wm-wrap'))return;try{var u=new URL(href,location.href);if(u.hostname===host||u.hostname==='')return;}catch(e){return;}
hasExt=true;a.dataset.vbExt=href;a.removeAttribute('href');a.style.cursor='pointer';});if(hasExt)vbBuildExtModal();}
function vbBuildExtModal(){var existing=document.getElementById('vbExtModal');if(existing)return existing;var modal=document.createElement('div');modal.id='vbExtModal';modal.innerHTML='<div class="vb-ext-box">'+'<div class="vb-ext-head"><i data-lucide="triangle-alert"></i> Forumdan Ayrılıyorsunuz</div>'+'<div class="vb-ext-body">'+'<div class="vb-ext-domain" id="vbExtDomain"></div>'+'<div class="vb-ext-msg">Bu bağlantı sizi <strong>MiFRM Forum</strong> dışındaki bir siteye yönlendiriyor.</div>'+'<div class="vb-ext-ad" id="vbExtAd" style="margin:10px 0;"></div>'+'</div>'+'<div class="vb-ext-btns">'+'<button class="vb-ext-back" type="button"><i data-lucide="arrow-left"></i> GERİ DÖN</button>'+'<button class="vb-ext-go" type="button">DEVAM ET <span id="vbExtSec"></span> <i data-lucide="arrow-right"></i></button>'+'</div></div>';document.body.appendChild(modal);vbIcons(modal);modal.querySelector('.vb-ext-back').onclick=function(){if(modal._vbIv){clearInterval(modal._vbIv);modal._vbIv=null;}modal.classList.remove('vb-ext-open');};modal.querySelector('.vb-ext-go').onclick=function(){modal.classList.remove('vb-ext-open');window.open(modal.dataset.vbDest,'_blank','noopener,noreferrer');};modal.addEventListener('click',function(e){if(e.target===modal){if(modal._vbIv){clearInterval(modal._vbIv);modal._vbIv=null;}modal.classList.remove('vb-ext-open');}});return modal;}
function vbExtCountdown(modal){var go=modal.querySelector('.vb-ext-go');var secEl=modal.querySelector('#vbExtSec');if(!go)return;if(modal._vbIv){clearInterval(modal._vbIv);modal._vbIv=null;}
var total=parseInt(MFG('linkRedirect.countdown',5),10);if(isNaN(total)||total<0)total=0;function done(){go.disabled=false;go.style.opacity='';if(secEl)secEl.textContent='';}
if(total<=0){done();return;}
var n=total;go.disabled=true;go.style.opacity='0.55';if(secEl)secEl.textContent='('+n+')';modal._vbIv=setInterval(function(){n--;if(n<=0){clearInterval(modal._vbIv);modal._vbIv=null;done();}
else if(secEl){secEl.textContent='('+n+')';}},1000);}
document.addEventListener('click',function(e){if(!e.target||!e.target.closest)return;var body=e.target.closest('.xf-post-body');if(!body)return;if(e.target.closest('img'))return;var a=e.target.closest('a[data-vb-ext]');if(!a||!body.contains(a))return;e.preventDefault();e.stopImmediatePropagation();var dest=a.dataset.vbExt||'';var modal=vbBuildExtModal();try{document.getElementById('vbExtDomain').textContent=new URL(dest,location.href).hostname;}
catch(err){document.getElementById('vbExtDomain').textContent=dest;}
var adEl=document.getElementById('vbExtAd');var ad=MFG('linkRedirect.adHtml','');if(adEl)adEl.innerHTML=ad||'';modal.dataset.vbDest=dest;modal.classList.add('vb-ext-open');vbExtCountdown(modal);},true);document.addEventListener('DOMContentLoaded',function(){vb404Init();vbExtInit();});window.xfShareKonu=function(btn){var titleEl=document.querySelector('.xf-post-title');var titleText=titleEl?(titleEl.innerText||titleEl.textContent||'').trim():document.title;var url=window.location.href;function doShare(shortUrl){var text="Konu '"+titleText+"' | MiFRM Forum\n"+shortUrl;if(navigator.share){navigator.share({title:titleText,text:text,url:shortUrl}).catch(function(){});}else{if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(function(){var orig=btn.innerHTML;btn.innerHTML='<i data-lucide="check" aria-hidden="true"></i>';vbIcons(btn);setTimeout(function(){btn.innerHTML=orig;},1800);});}}}
fetch('https://is.gd/create.php?format=json&url='+encodeURIComponent(url)).then(function(r){return r.ok?r.json():null;}).then(function(d){doShare((d&&d.shorturl)?d.shorturl:url);}).catch(function(){doShare(url);});};}());function loadSimilarTopics(){var block=document.getElementById('vb-similar-topics');var listEl=document.getElementById('vb-similar-list');if(!block||!listEl)return;var labelLinks=document.querySelectorAll('.hm-breadcrumb a[href*="/search/label/"]');var label='';if(labelLinks.length){var href=labelLinks[labelLinks.length-1].getAttribute('href');var m=href.match(/\/search\/label\/([^?#]+)/);if(m)label=decodeURIComponent(m[1].replace(/\+/g,' '));}
var feedUrl=label?'/feeds/posts/summary/-/'+encodeURIComponent(label)+'?alt=json&max-results=20':'/feeds/posts/summary?alt=json&orderby=published&max-results=20';var currentUrl=location.href.split('#')[0].split('?')[0];cachedFetch(feedUrl).then(function(data){var entries=(data&&data.feed&&data.feed.entry)||[];var filtered=entries.filter(function(e){var lnk=getAltLink(e);if(!lnk)return false;return lnk.href.split('#')[0].split('?')[0]!==currentUrl;});if(!filtered.length){block.style.display='none';return;}
var html='';filtered.slice(0,MFG('similarTopics.count',6)).forEach(function(e){var lnk=getAltLink(e);var url=lnk?lnk.href:'#';var title=safeText(e.title?e.title.$t:'');var author=safeText(getAuthorName(e));var avatar=getAuthorImg(e);var avatarHtml=avatar?'<img src="'+avatar+'" alt="'+author+'" loading="lazy" width="32" height="32"/>':'<i data-lucide="user" aria-hidden="true"></i>';var date=formatDate(e.published?e.published.$t:'');var replies=e['thr$total']?String(e['thr$total'].$t):'0';var cat=(e.category&&e.category.length)?safeText(e.category[0].term):'';var catHtml=cat?'<span class="vb-cat-badge"><i data-lucide="'+getCategoryIcon(cat)+'" aria-hidden="true"></i>'+cat+'</span>':'';html+='<div class="hamdi-forum-row">'
+'<div class="hamdi-avatar-holder" aria-hidden="true">'+avatarHtml
+'<div class="hamdi-status-dot"></div></div>'
+'<div class="hamdi-main-info">'
+'<div class="hamdi-title"><a href="'+url+'">'+title+'</a></div>'
+'<div class="hamdi-meta">'+catHtml
+'<i data-lucide="user" aria-hidden="true" style="margin-right:3px"></i>'
+'<span class="hamdi-author">'+author+'</span> &middot; '+date+'</div>'
+'</div>'
+'<div class="hamdi-replies-zone"><i data-lucide="message-circle" aria-hidden="true" style="margin-right:3px"></i>'+replies+'</div>'
+'<div class="hamdi-arrow-zone" aria-hidden="true"><i data-lucide="chevron-right"></i></div>'
+'</div>';});listEl.innerHTML=html;vbIcons(listEl);block.style.display='';buildAvatarCache(entries);applyAvatarCache();}).catch(function(){block.style.display='none';});}
document.addEventListener('DOMContentLoaded',function(){if(document.getElementById('vb-similar-topics'))loadSimilarTopics();});(function(){var loaded=false;function loadGsi(){if(loaded)return;loaded=true;var s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;document.head.appendChild(s);}
if(typeof window.requestIdleCallback==='function'){requestIdleCallback(loadGsi,{timeout:4000});}else{window.addEventListener('load',function(){setTimeout(loadGsi,1500);});}
document.addEventListener('DOMContentLoaded',function(){var btn=document.getElementById('mifrm-nav-btn');if(btn)btn.addEventListener('click',loadGsi,{once:true});});})();
